"""Agent-modifiable profile configurations for Polymarket crypto predictions.

Each profile tunes the edge detection strategy: how aggressive to bet,
which indicators to weight more, how early to evaluate before resolution.
"""

ACTIVE_PROFILE = "aggressive_edge"

PROFILE_CONFIGS = {
    "balanced_edge": {
        "bankroll": 1000,
        "min_edge_pct": 5.0,
        "kelly_fraction_cap": 0.008,
        "max_bet_fraction": 0.004,
        "min_volume": 1000,
        "min_liquidity": 500,
        "calibration_method": "heuristic",
        "confidence_threshold": 0.15,
        "eval_point_days_before": 1,
        "crypto_indicator_weight": 0.25,
        "rsi_weight": 0.10,
        "macd_weight": 0.30,
        "trend_weight": 0.10,
        "bb_weight": 0.10,
        "momentum_weight": 0.40,
    },

    "aggressive_edge": {
        "bankroll": 1000,
        "min_edge_pct": 4.0,
        "kelly_fraction_cap": 0.008,
        "max_bet_fraction": 0.004,
        "min_volume": 500,
        "min_liquidity": 200,
        "calibration_method": "heuristic",
        "confidence_threshold": 0.15,
        "eval_point_days_before": 1,
        "crypto_indicator_weight": 0.25,
        "rsi_weight": 0.05,
        "macd_weight": 0.35,
        "trend_weight": 0.10,
        "bb_weight": 0.10,
        "momentum_weight": 0.40,
    },

    "conservative_edge": {
        "bankroll": 1000,
        "min_edge_pct": 5.0,
        "kelly_fraction_cap": 0.008,
        "max_bet_fraction": 0.004,
        "min_volume": 1000,
        "min_liquidity": 500,
        "calibration_method": "heuristic",
        "confidence_threshold": 0.15,
        "eval_point_days_before": 1,
        "crypto_indicator_weight": 0.25,
        "rsi_weight": 0.10,
        "macd_weight": 0.30,
        "trend_weight": 0.10,
        "bb_weight": 0.10,
        "momentum_weight": 0.40,
    },

    "trend_follower": {
        "bankroll": 1000,
        "min_edge_pct": 5.0,
        "kelly_fraction_cap": 0.0075,
        "max_bet_fraction": 0.00375,
        "min_volume": 1000,
        "min_liquidity": 500,
        "calibration_method": "heuristic",
        "confidence_threshold": 0.15,
        "eval_point_days_before": 1,
        "crypto_indicator_weight": 0.30,
        "rsi_weight": 0.05,
        "macd_weight": 0.35,
        "trend_weight": 0.25,
        "bb_weight": 0.05,
        "momentum_weight": 0.30,
    },

    "mean_reversion": {
        "bankroll": 1000,
        "min_edge_pct": 5.0,
        "kelly_fraction_cap": 0.0075,
        "max_bet_fraction": 0.00375,
        "min_volume": 1000,
        "min_liquidity": 500,
        "calibration_method": "heuristic",
        "confidence_threshold": 0.15,
        "eval_point_days_before": 1,
        "crypto_indicator_weight": 0.40,
        "rsi_weight": 0.45,
        "macd_weight": 0.05,
        "trend_weight": 0.05,
        "bb_weight": 0.40,
        "momentum_weight": 0.05,
    },
}
