"""Agent-modifiable profile configurations for Polymarket crypto predictions.

Each profile tunes the edge detection strategy: how aggressive to bet,
which indicators to weight more, how early to evaluate before resolution.
"""

ACTIVE_PROFILE = "balanced_edge"

PROFILE_CONFIGS = {
    "balanced_edge": {
        "bankroll": 1000,
        "min_edge_pct": 5.0,
        "kelly_fraction_cap": 0.10,
        "max_bet_fraction": 0.05,
        "min_volume": 1000,
        "min_liquidity": 500,
        "calibration_method": "heuristic",
        "confidence_threshold": 0.3,
        "eval_point_days_before": 7,
        "crypto_indicator_weight": 0.6,
        "rsi_weight": 0.25,
        "macd_weight": 0.20,
        "trend_weight": 0.25,
        "bb_weight": 0.15,
        "momentum_weight": 0.15,
    },

    "aggressive_edge": {
        "bankroll": 1000,
        "min_edge_pct": 2.0,
        "kelly_fraction_cap": 0.15,
        "max_bet_fraction": 0.08,
        "min_volume": 500,
        "min_liquidity": 200,
        "calibration_method": "heuristic",
        "confidence_threshold": 0.2,
        "eval_point_days_before": 5,
        "crypto_indicator_weight": 0.7,
        "rsi_weight": 0.15,
        "macd_weight": 0.15,
        "trend_weight": 0.20,
        "bb_weight": 0.15,
        "momentum_weight": 0.35,
    },

    "conservative_edge": {
        "bankroll": 1000,
        "min_edge_pct": 10.0,
        "kelly_fraction_cap": 0.06,
        "max_bet_fraction": 0.03,
        "min_volume": 5000,
        "min_liquidity": 2000,
        "calibration_method": "heuristic",
        "confidence_threshold": 0.5,
        "eval_point_days_before": 14,
        "crypto_indicator_weight": 0.5,
        "rsi_weight": 0.30,
        "macd_weight": 0.25,
        "trend_weight": 0.25,
        "bb_weight": 0.10,
        "momentum_weight": 0.10,
    },

    "trend_follower": {
        "bankroll": 1000,
        "min_edge_pct": 4.0,
        "kelly_fraction_cap": 0.12,
        "max_bet_fraction": 0.06,
        "min_volume": 1000,
        "min_liquidity": 500,
        "calibration_method": "heuristic",
        "confidence_threshold": 0.25,
        "eval_point_days_before": 7,
        "crypto_indicator_weight": 0.7,
        "rsi_weight": 0.10,
        "macd_weight": 0.30,
        "trend_weight": 0.35,
        "bb_weight": 0.10,
        "momentum_weight": 0.15,
    },

    "mean_reversion": {
        "bankroll": 1000,
        "min_edge_pct": 6.0,
        "kelly_fraction_cap": 0.08,
        "max_bet_fraction": 0.04,
        "min_volume": 2000,
        "min_liquidity": 1000,
        "calibration_method": "heuristic",
        "confidence_threshold": 0.35,
        "eval_point_days_before": 3,
        "crypto_indicator_weight": 0.65,
        "rsi_weight": 0.40,
        "macd_weight": 0.10,
        "trend_weight": 0.10,
        "bb_weight": 0.30,
        "momentum_weight": 0.10,
    },
}
